-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Client"
(
    "ClientID" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "FirstName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "LastName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Gender" character(1) COLLATE pg_catalog."default",
    "MobileNumber" character(9) COLLATE pg_catalog."default",
    "YearOfBirth" integer,
    CONSTRAINT "Client_pk" PRIMARY KEY ("ClientID")
);

CREATE TABLE IF NOT EXISTS public."Package"
(
    "PackageCode" character(8) COLLATE pg_catalog."default" NOT NULL,
    "Destination" character varying(100) COLLATE pg_catalog."default",
    "TransportType" character varying(50) COLLATE pg_catalog."default",
    "AccommodationType" character varying(50) COLLATE pg_catalog."default",
    "ClientID" character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT "Package_pkey" PRIMARY KEY ("PackageCode")
);

CREATE TABLE IF NOT EXISTS public."Reservation"
(
    "ReservationID" character varying(8) COLLATE pg_catalog."default" NOT NULL,
    "TravelDate" date NOT NULL,
    "NumberOfPeople" integer,
    "PackageCode" character(8) COLLATE pg_catalog."default" NOT NULL,
    "Price" numeric(11, 2) NOT NULL,
    CONSTRAINT "Reservation_pk" PRIMARY KEY ("ReservationID"),
    CONSTRAINT "Reservation_one_per_package" UNIQUE ("PackageCode")
);

ALTER TABLE IF EXISTS public."Package"
    ADD CONSTRAINT "Package_ClientID_fkey" FOREIGN KEY ("ClientID")
    REFERENCES public."Client" ("ClientID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Reservation"
    ADD CONSTRAINT "Reservation_Package_fk" FOREIGN KEY ("PackageCode")
    REFERENCES public."Package" ("PackageCode") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "Reservation_one_per_package"
    ON public."Reservation"("PackageCode");

END;